### ISSUE TITLE
Why is __moduleName given to CSSLoader?

### ISSUE THREAD

**Issue by MeoMix** [geelen/jspm-loader-css#43]
The variable `__moduleName` is passed into CSSLoader's constructor and stored as a private variable, `_moduleName`, but it is then never used.

Is this just sloppy coding? Or were their plans for it in the future that didn't make it into this?

**Comment by geelen** [comment]
The idea was that `jspm-loader-css-modules` would reuse `jspm-loader-css` but when it found an `:import` directive it would need to know to load using the right loader. But I think there's a better way to do this now.

**Comment by MeoMix** [comment]
I'll go ahead and remove it on muh branch.

**Comment by MeoMix** [comment]
Removed on muh branch.
