### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by andywer** [geelen/jspm-loader-css#50]
Hi Glen!
Could you please release the current master branch using a new version number?
We really need the fix https://github.com/geelen/jspm-loader-css/commit/afd2d807c5d602d7a8606b33d2fc4faf44db2b00 in order to not crash and burn when trying to import from another package (like `@value blue, green from 'fancypackage/colors.css'`) :)

Nice work, though!

**Comment by geelen** [comment]
Done. `v1.1.0` is out!

**Comment by andywer** [comment]
Thanks!
